/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Granularity = IDL.Variant({
  'hourly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const TimeRangeFilter = IDL.Record({
  'startTime' : IDL.Opt(Timestamp),
  'endTime' : IDL.Opt(Timestamp),
  'granularity' : Granularity,
});
export const BurnRateSnapshot = IDL.Record({
  'cyclesPerHour' : IDL.Nat,
  'cyclesPerWeek' : IDL.Nat,
  'cyclesPerDay' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const BurnRateRangeResult = IDL.Record({
  'granularity' : Granularity,
  'snapshots' : IDL.Vec(BurnRateSnapshot),
});
export const BurnRateSummary = IDL.Record({
  'history' : IDL.Vec(BurnRateSnapshot),
  'current' : BurnRateSnapshot,
});

export const idlService = IDL.Service({
  'getBurnRateForRange' : IDL.Func(
      [TimeRangeFilter],
      [BurnRateRangeResult],
      ['query'],
    ),
  'getBurnRateHistory' : IDL.Func([], [BurnRateSummary], ['query']),
  'getCurrentBurnRates' : IDL.Func([], [BurnRateSnapshot], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Granularity = IDL.Variant({
    'hourly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const TimeRangeFilter = IDL.Record({
    'startTime' : IDL.Opt(Timestamp),
    'endTime' : IDL.Opt(Timestamp),
    'granularity' : Granularity,
  });
  const BurnRateSnapshot = IDL.Record({
    'cyclesPerHour' : IDL.Nat,
    'cyclesPerWeek' : IDL.Nat,
    'cyclesPerDay' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const BurnRateRangeResult = IDL.Record({
    'granularity' : Granularity,
    'snapshots' : IDL.Vec(BurnRateSnapshot),
  });
  const BurnRateSummary = IDL.Record({
    'history' : IDL.Vec(BurnRateSnapshot),
    'current' : BurnRateSnapshot,
  });
  
  return IDL.Service({
    'getBurnRateForRange' : IDL.Func(
        [TimeRangeFilter],
        [BurnRateRangeResult],
        ['query'],
      ),
    'getBurnRateHistory' : IDL.Func([], [BurnRateSummary], ['query']),
    'getCurrentBurnRates' : IDL.Func([], [BurnRateSnapshot], []),
  });
};

export const init = ({ IDL }) => { return []; };