/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BurnRateRangeResult {
  'granularity' : Granularity,
  'snapshots' : Array<BurnRateSnapshot>,
}
export interface BurnRateSnapshot {
  'cyclesPerHour' : bigint,
  'cyclesPerWeek' : bigint,
  'cyclesPerDay' : bigint,
  'timestamp' : Timestamp,
}
export interface BurnRateSummary {
  'history' : Array<BurnRateSnapshot>,
  'current' : BurnRateSnapshot,
}
export type Granularity = { 'hourly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface TimeRangeFilter {
  'startTime' : [] | [Timestamp],
  'endTime' : [] | [Timestamp],
  'granularity' : Granularity,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getBurnRateForRange' : ActorMethod<[TimeRangeFilter], BurnRateRangeResult>,
  'getBurnRateHistory' : ActorMethod<[], BurnRateSummary>,
  'getCurrentBurnRates' : ActorMethod<[], BurnRateSnapshot>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];